PROJECT = crash_landing
BUILD_DIR = build

CFILES = crash_landing.c

DEVICE=stm32f205tft6

OPENCM3_DIR=./libopencm3

include $(OPENCM3_DIR)/mk/genlink-config.mk
include rules.mk
include $(OPENCM3_DIR)/mk/genlink-rules.mk